---
- include_tasks: network.yml
  when: vaultwarden_enabled == "true"

- include_tasks: start.yml
  when: vaultwarden_enabled == "true"

- include_tasks: stop.yml
  when: vaultwarden_enabled == "false"